version: '3'

services:

  wordpress:
    image: wordpress
    ports:
      - "8089:80"
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: sagar
      WORDPRESS_DB_NAME: wordpress
    networks:
      test:
        ipv4_address: "10.56.1.21"


  mysql:
    image: "mysql:5.7"

    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: sagar
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      test:
        ipv4_address: "10.56.1.20"

networks:
  test:
    ipam:
      driver: default